// Generated by CoffeeScript 1.7.1
var populate;

populate = function() {
  var i, _i, _results;
  _results = [];
  for (i = _i = 1; _i <= 3; i = ++_i) {
    _results.push(i);
  }
  return _results;
};
